const SOURCES={
  pessoas:{id:'1XAH58-6rwC0kFHVwKlgvknFjLjLE-S7d',sheets:{asos:'Gestão de ASOS',treinos:'Treinamentos Obrigatórios',horas:'Horas Treinadas',recusa:'Direito de Recusa (Aplicação)',atestados:'Atestados',pare:'PARE (Aplicação)'}},
  processos:{id:'1v0gp-iixQYqfZ2ah68clCmf_PdGv9Ydz',sheets:{nota:'Avaliação de Contratadas (MVV)',dds:'DDS (Participação)',temas:'DDS (Temas Abordados)',inspecoes:'Inspeções Mensais de Segurança',vct:'VCT',docs:'Validade de documentos e Laudos',comiss:'Validade de Comissionameno)',acidentes:'Acidentes e Incidentes',epis:'Gestão de EPIS',fardamentos:'Gestão de Fardamentos '}}
};
const $=s=>document.querySelector(s);let cache={};
const clean=v=>String(v??'').trim();
const filled=(rows,i=0)=>rows.filter(r=>clean(r[i]));
function num(v){if(typeof v==='number')return v;return Number(clean(v).replace('%','').replace('.','').replace(',','.'))||0}
function pct(v){const n=num(v);return n<=1?n*100:n}
function date(v){if(!v)return null;const m=String(v).match(/Date\((\d+),(\d+),(\d+)\)/);if(m)return new Date(+m[1],+m[2],+m[3]);const d=new Date(v);return isNaN(d)?null:d}
function fmtDate(v){const d=date(v);return d?d.toLocaleDateString('pt-BR'):'—'}
function statusDate(v){const d=date(v);if(!d)return ['Sem data','warn'];return d<new Date()?['Vencido','danger']:['Vigente','good']}
function url(id,sheet){return `https://docs.google.com/spreadsheets/d/${id}/gviz/tq?tqx=out:json&range=A1:CU1000&sheet=${encodeURIComponent(sheet)}`}
async function load(id,sheet){const key=id+sheet;if(cache[key])return cache[key];const res=await fetch(url(id,sheet));if(!res.ok)throw Error(`falha ao acessar a aba ${sheet}`);const raw=await res.text();const j=JSON.parse(raw.replace(/^[^(]*\(/,'').replace(/\);?\s*$/,''));return cache[key]={cols:j.table.cols.map(c=>c.label||''),rows:j.table.rows.map(r=>r.c.map(c=>c?.v??''))}}
function metric(label,value,note,kind=''){return `<article class="metric ${kind}"><div class="metric-label">${label}</div><div class="metric-value">${value}</div><div class="metric-note">${note}</div></article>`}
function line(values,labels){const max=Math.max(1,...values),w=700,h=190,p=28;const pts=values.map((v,i)=>`${p+i*(w-p*2)/Math.max(1,values.length-1)},${h-p-(v/max)*(h-p*2)}`).join(' ');return `<svg viewBox="0 0 ${w} ${h+18}" preserveAspectRatio="none">${[0,.5,1].map(x=>`<line class="gridline" x1="${p}" x2="${w-p}" y1="${h-p-x*(h-p*2)}" y2="${h-p-x*(h-p*2)}"/>`).join('')}<polyline class="line-red" points="${pts}"/>${values.map((v,i)=>`<circle class="dot" data-tooltip="${labels[i]}: ${v}" aria-label="${labels[i]}: ${v}" cx="${p+i*(w-p*2)/Math.max(1,values.length-1)}" cy="${h-p-(v/max)*(h-p*2)}" r="4"><title>${labels[i]}: ${v}</title></circle>`).join('')}${labels.map((l,i)=>`<text class="axis" x="${p+i*(w-p*2)/Math.max(1,labels.length-1)}" y="${h+1}" text-anchor="middle">${l}</text>`).join('')}</svg><div class="chart-tooltip" role="status" aria-live="polite"></div>`}
function bars(values,labels){const max=Math.max(1,...values),w=700,h=190,p=28,bw=Math.min(50,(w-p*2)/Math.max(1,values.length)-12);return `<svg viewBox="0 0 ${w} ${h+18}" preserveAspectRatio="none">${[0,.5,1].map(x=>`<line class="gridline" x1="${p}" x2="${w-p}" y1="${h-p-x*(h-p*2)}" y2="${h-p-x*(h-p*2)}"/>`).join('')}${values.map((v,i)=>{const x=p+i*(w-p*2)/Math.max(1,values.length-1)-bw/2,bh=(v/max)*(h-p*2);return `<rect class="bar" data-tooltip="${labels[i]}: ${v}" aria-label="${labels[i]}: ${v}" x="${x}" y="${h-p-bh}" width="${bw}" height="${bh}" rx="2"><title>${labels[i]}: ${v}</title></rect>`}).join('')}${labels.map((l,i)=>`<text class="axis" x="${p+i*(w-p*2)/Math.max(1,labels.length-1)}" y="${h+1}" text-anchor="middle">${l}</text>`).join('')}</svg><div class="chart-tooltip" role="status" aria-live="polite"></div>`}
function panel(title,kicker,body,wide=false){return `<article class="panel ${wide?'wide':''}"><div class="panel-head"><div><div class="panel-kicker">${kicker}</div><h3>${title}</h3></div></div>${body}</article>`}
function section(id,number,title,desc,body){return `<section id="${id}" class="section"><div class="section-header"><div class="section-title"><span>${number}</span><h2>${title}</h2></div><p>${desc}</p></div>${body}</section>`}
function table(id,headers,rows,placeholder){return `<div class="table-tools"><input data-filter="${id}" placeholder="${placeholder}" aria-label="Filtrar tabela"><small><span id="${id}-count">${rows.length}</span> registros</small></div><div class="table-wrap"><table class="data-table" id="${id}"><thead><tr>${headers.map((h,i)=>`<th><button data-sort="${i}">${h}</button></th>`).join('')}</tr></thead><tbody>${rows.join('')}</tbody></table></div>`}
function wireTables(){document.querySelectorAll('[data-filter]').forEach(input=>input.addEventListener('input',()=>{const t=$('#'+input.dataset.filter),q=input.value.toLowerCase();let count=0;t.querySelectorAll('tbody tr').forEach(r=>{const show=r.textContent.toLowerCase().includes(q);r.hidden=!show;if(show)count++});$('#'+input.dataset.filter+'-count').textContent=count}));document.querySelectorAll('[data-sort]').forEach(btn=>btn.addEventListener('click',()=>{const t=btn.closest('table'),body=t.tBodies[0],idx=Number(btn.dataset.sort),rows=[...body.rows];const dir=btn.dataset.dir==='asc'?'desc':'asc';btn.dataset.dir=dir;rows.sort((a,b)=>{const x=a.cells[idx].textContent.trim(),y=b.cells[idx].textContent.trim();return dir==='asc'?x.localeCompare(y,'pt-BR',{numeric:true}):y.localeCompare(x,'pt-BR',{numeric:true})});rows.forEach(r=>body.appendChild(r))}))}
function wireCharts(){document.querySelectorAll('.chart [data-tooltip]').forEach(point=>{const chart=point.closest('.chart'),tip=chart.querySelector('.chart-tooltip');const show=e=>{tip.textContent=point.dataset.tooltip;tip.classList.add('show');const box=chart.getBoundingClientRect();tip.style.left=`${Math.max(8,Math.min(box.width-150,e.clientX-box.left+10))}px`;tip.style.top=`${Math.max(8,e.clientY-box.top-42)}px`};point.addEventListener('pointerenter',show);point.addEventListener('pointermove',show);point.addEventListener('pointerleave',()=>tip.classList.remove('show'))})}
function wireNavigation(){const links=[...document.querySelectorAll('.anchor-nav a')],sections=links.map(link=>document.querySelector(link.getAttribute('href'))).filter(Boolean);const activate=id=>links.forEach(link=>link.classList.toggle('active',link.getAttribute('href')===`#${id}`));links.forEach(link=>link.addEventListener('click',()=>activate(link.getAttribute('href').slice(1))));const update=()=>{const current=sections.reduce((chosen,section)=>section.getBoundingClientRect().top<=150?section:chosen,sections[0]);if(current)activate(current.id)};window.addEventListener('scroll',update,{passive:true});update()}
async function buildPessoas(){const s=SOURCES.pessoas;const vals=await Promise.all(Object.values(s.sheets).map(n=>load(s.id,n)));const [a,t,h,r,at,p]=vals.map(x=>filled(x.rows));const today=new Date();const valid=a.map(x=>date(x[4])).filter(Boolean);const venc=valid.filter(x=>x<today).length;const months=['Jan','Fev','Mar','Abr','Mai','Jun','Jul'];const asoMonthly=months.map((_,i)=>a.filter(x=>{const d=date(x[3]);return d&&d.getMonth()===i}).length);const hoursMonthly=months.map((_,i)=>h.reduce((sum,row)=>sum+num(row[4+i*3]),0));const statusCounts=[valid.filter(x=>x>=today).length,venc,a.length-valid.length];const asoRows=a.map(x=>{const st=statusDate(x[4]);return `<tr><td><strong>${clean(x[2])||'—'}</strong></td><td>${clean(x[1])||'—'}</td><td>${fmtDate(x[3])}</td><td>${fmtDate(x[4])}</td><td><span class="badge ${st[1]}">${st[0]}</span></td></tr>`});const peoplePanel=panel('Colaboradores e validade do ASO','Tabela de gestão',table('aso-table',['Colaborador','Matrícula','Último ASO','Validade','Situação'],asoRows,'Buscar por nome, matrícula ou situação'),true);return section('pessoas','01','Pessoas','Saúde ocupacional, capacitação e prontidão da equipe',`<div class="metrics">${metric('Colaboradores na base',a.length,'registros de ASO','good')}${metric('ASOs vencidos',venc,'comparado com hoje',venc?'alert':'good')}${metric('Treinamentos registrados',t.length,'linhas preenchidas')}${metric('Atestados registrados',at.length,'acompanhamentos na base')}</div><div class="grid">${panel('ASOs emitidos por mês','Gestão de ASOs',`<div class="chart">${line(asoMonthly,months)}</div><div class="legend"><span><b></b>Registros de ASO</span></div>`)}${panel('Horas de treinamento por mês','Capacitação',`<div class="chart">${bars(hoursMonthly,months)}</div><div class="legend"><span><b class="ink"></b>Horas informadas</span></div>`)}${panel('Cobertura do controle','Situação atual',`<div class="list"><div class="list-row"><strong>Validades vigentes</strong><span class="badge">${statusCounts[0]}</span></div><div class="list-row"><strong>Validades vencidas</strong><span class="badge ${venc?'danger':''}">${statusCounts[1]}</span></div><div class="list-row"><strong>Sem data de validade</strong><span class="badge ${statusCounts[2]?'warn':''}">${statusCounts[2]}</span></div><div class="list-row"><strong>Direito de recusa / PARE</strong><span class="badge">${r.length} / ${p.length}</span></div></div>`)}${panel('Leitura para gestão','O que mudou',`<p class="footnote">“Monitorado” foi removido. Agora cada colaborador aparece com a situação objetiva do ASO: vigente, vencido ou sem data registrada. Use a busca para localizar registros rapidamente.</p><div class="list"><div class="list-row"><strong>Colaboradores com treinamento</strong><span class="badge">${t.length}</span></div><div class="list-row"><strong>Colaboradores com horas lançadas</strong><span class="badge">${h.length}</span></div></div>`)}${peoplePanel}</div>`)}
async function buildProcessos(){const s=SOURCES.processos;const vals=await Promise.all(Object.values(s.sheets).map(n=>load(s.id,n)));const [n,d,temas,i,v,docs,c,ac,epi,far]=vals.map(x=>filled(x.rows));const scores=n.map(x=>pct(x[2])).filter(Boolean);const average=scores.length?Math.round(scores.reduce((a,b)=>a+b,0)/scores.length):0;const today=new Date();const venc=docs.filter(x=>{const d=date(x[3]);return d&&d<today}).length;const zero=epi.filter(x=>num(x[4])===0).length+far.filter(x=>num(x[3])===0).length;const months=['Jan','Fev','Mar','Abr','Mai','Jun','Jul'];const scoreMonthly=months.map((_,m)=>{const z=n.filter(x=>{const d=date(x[1]);return d&&d.getMonth()===m}).map(x=>pct(x[2])).filter(Boolean);return z.length?Math.round(z.reduce((a,b)=>a+b,0)/z.length):0});const volume=[n.length,d.length,i.length,v.length,docs.length,c.length,temas.length];const volumeLabels=['Notas','DDS','Inspeções','VCT','Documentos','Comiss.','Temas'];const docsRows=docs.map(x=>{const st=statusDate(x[3]);return `<tr><td><strong>${clean(x[1])||'—'}</strong></td><td>${fmtDate(x[2])}</td><td>${fmtDate(x[3])}</td><td><span class="badge ${st[1]}">${st[0]}</span></td></tr>`});const stockRows=[...epi.map(x=>[clean(x[1]),clean(x[2]),clean(x[4]),'EPI']),...far.map(x=>[clean(x[1]),clean(x[2]),clean(x[3]),'Fardamento'])].map(x=>`<tr><td><strong>${x[0]||'—'}</strong></td><td>${x[1]||'—'}</td><td><span class="badge ${num(x[2])===0?'danger':''}">${x[2]||'—'}</span></td><td>${x[3]}</td></tr>`);return section('processos','02','Processos','Disciplina operacional, validade documental e prevenção de desvios',`<div class="metrics">${metric('Nota média de contratadas',average?average+'%':'—','avaliações preenchidas','good')}${metric('DDS registrados',d.length,'participação e temas')}${metric('Inspeções realizadas',i.length,'checklists na base')}${metric('Pontos de atenção',venc+zero,'validade + estoque',venc+zero?'alert':'good')}</div><div class="grid">${panel('Aderência da operação','Avaliação de contratadas',`<div class="chart">${line(scoreMonthly,months)}</div><div class="legend"><span><b></b>Nota média mensal</span></div>`)}${panel('Volume por frente de controle','Relação entre processos',`<div class="chart">${bars(volume,volumeLabels)}</div><div class="legend"><span><b class="ink"></b>Registros por aba</span></div>`)}${panel('Documentos e laudos','Controle de validade',table('docs-table',['Documento / laudo','Elaboração','Vigência','Situação'],docsRows,'Buscar documento ou situação'),true)}${panel('EPIs e fardamentos','Estoque atual',table('stock-table',['Item','Localização / tamanho','Estoque','Grupo'],stockRows,'Buscar item, grupo ou estoque'),true)}</div>`)}
async function render(){const root=$('#dashboard');root.innerHTML='<div class="loading"><div class="spinner"></div><p>Atualizando indicadores…</p></div>';try{root.innerHTML=await buildPessoas()+await buildProcessos();wireTables();wireCharts();wireNavigation()}catch(e){root.innerHTML=`<div class="error"><strong>Não foi possível atualizar os indicadores.</strong><span>${e.message}. Verifique se as planilhas continuam publicadas para visualização.</span></div>`}}
render();
